version: "3.9"
services:
  api:
    build: .
    ports: 
     - "5000:3000" 
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
